language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
env:
  - "TASK=test:core_and_plugins"
  - "TASK=test:rails RAILS=master"
  - "TASK=test:rails RAILS=3.0.20"
  - "TASK=test:rails RAILS=3.1.12"
  - "TASK=test:rails RAILS=3.2.13"
  - "TASK=test:rails RAILS=4.0.0.beta1"
  - "TASK=test:sinatra SINATRA=master"
  - "TASK=test:sinatra SINATRA=1.3.6"
  - "TASK=test:sinatra SINATRA=1.4.2"
  - "TASK=bench iterations=10000"
  - "TASK=bench slow=1 iterations=1000"
matrix:
  exclude:
    # Test Rails master only on 1.9.3+ Rubies
    - rvm: 1.8.7
      env: "TASK=test:rails RAILS=master"
    - rvm: jruby-18mode
      env: "TASK=test:rails RAILS=master"
    - rvm: rbx-18mode
      env: "TASK=test:rails RAILS=master"
    - rvm: 1.8.7
      env: "TASK=test:rails RAILS=4.0.0.beta1"
    - rvm: jruby-18mode
      env: "TASK=test:rails RAILS=4.0.0.beta1"
    - rvm: rbx-18mode
      env: "TASK=test:rails RAILS=4.0.0.beta1"
  allow_failures:
    - env: "TASK=test:rails RAILS=master"
    - env: "TASK=test:rails RAILS=4.0.0.beta1"
    - env: "TASK=test:sinatra SINATRA=master"
    - env: "TASK=test:rails RAILS=3.0.20"
      rvm: 2.0.0
    - rvm: ruby-head
# Rails master needs newest bundler
before_install:
  - ./kill-travis.sh
  - gem update bundler
script: "bundle exec rake $TASK"
