rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby
  - rbx-2.0
env:
  - "TASK=test"
  - "TASK=test TEMPLE=master"
  - "TASK=test:rails TEMPLE=master RAILS=master"
  - "TASK=test:rails RAILS=3.0.10"
script: "bundle exec rake test:ci"
notifications:
  email: false
  irc:
    - "irc.freenode.org#slim-lang"
