language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-2
env:
  - "TASK=test:core_and_plugins TILT=master"
  - "TASK=test:core_and_plugins TILT=1.3.7"
  - "TASK=test:core_and_plugins TILT=1.4.1"
  - "TASK=test:core_and_plugins TILT=2.0.1"
  - "TASK=test:rails RAILS=master"
  - "TASK=test:rails RAILS=3.0.20"
  - "TASK=test:rails RAILS=3.1.12 TILT=1.3.4"
  - "TASK=test:rails RAILS=3.2.17 TILT=1.3.4"
  - "TASK=test:rails RAILS=4.0.4"
  - "TASK=test:rails RAILS=4.1.0"
  - "TASK=test:sinatra SINATRA=master"
  - "TASK=test:sinatra SINATRA=1.3.6"
  - "TASK=test:sinatra SINATRA=1.4.5"
  - "TASK=bench iterations=10000"
  - "TASK=bench slow=1 iterations=1000"
matrix:
  exclude:
    # Test Rails master only on 1.9.3+ Rubies
    - rvm: 1.8.7
      env: "TASK=test:rails RAILS=master"
    - rvm: jruby-18mode
      env: "TASK=test:rails RAILS=master"
    - rvm: rbx-2
      env: "TASK=test:rails RAILS=master"
    - rvm: 1.8.7
      env: "TASK=test:rails RAILS=4.0.4"
    - rvm: 1.8.7
      env: "TASK=test:rails RAILS=4.1.0"
    - rvm: jruby-18mode
      env: "TASK=test:rails RAILS=4.0.4"
    - rvm: jruby-18mode
      env: "TASK=test:rails RAILS=4.1.0"
  allow_failures:
    - env: "TASK=test:core_and_plugins TILT=master"
    - env: "TASK=test:rails RAILS=master"
    - env: "TASK=test:sinatra SINATRA=master"
      rvm: 2.0.0
    - rvm: ruby-head
# Rails master needs newest bundler
before_install:
  - gem update bundler
script: "bundle exec rake $TASK"
