rvm:
  - 1.8.7
  - 1.9.3
  - ruby-head
  - jruby
  - rbx-18mode
  - rbx-19mode
env:
  - "TASK=test"
  - "TASK=test:rails RAILS=master"
  - "TASK=test:rails RAILS=3.0.11"
  - "TASK=test:rails RAILS=3.1.3"
matrix:
  exclude:
    # Test Rails master only on 1.9.3+ Rubies
    - rvm: 1.8.7
      env: "TASK=test:rails RAILS=master"
    - rvm: jruby
      env: "TASK=test:rails RAILS=master"
    - rvm: rbx-18mode
      env: "TASK=test:rails RAILS=master"
  allow_failures:
    - rvm: ruby-head
    - env: "TASK=test:rails RAILS=master"
script: "bundle exec rake test:ci"
notifications:
  email: false
  irc:
    - "irc.freenode.org#slim-lang"
