language: ruby

rvm:
  - ruby-head
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - 2.0.0
  - rbx-3
  - jruby-head
  - jruby-19mode

sudo: false
dist: trusty

script: "bundle exec rake $TASK"

after_success:
  - bundle exec codeclimate-test-reporter

env:
  global:
    # travis encrypt CODECLIMATE_REPO_TOKEN=???
    - secure: "a7sD9iwPJJn3Fj+mn62GAmy/PEguh3elrilsp1KS+WfDiCiIKD8Q5KG2Jv67DGcQAGI3dPWeh7+ZhZ/W7nEipwWUBmSvGYVeoF63y8j6mNRLeekqspj94l47hXyFePj9bCadY1b1/xY4lE1pMEU8eA8AOUHUqCSuH+Kk/MuvyLM="
  matrix:
    - "TASK=test:core_and_plugins TILT=master"
    - "TASK=test:core_and_plugins TILT=1.3.7"
    - "TASK=test:core_and_plugins TILT=1.4.1"
    - "TASK=test:core_and_plugins TILT=2.0.1"
    - "TASK=test:rails RAILS=master"
    - "TASK=test:rails RAILS=3.1.12 TILT=1.3.4"
    - "TASK=test:rails RAILS=3.2.21 TILT=1.3.4"
    - "TASK=test:rails RAILS=4.0.13"
    - "TASK=test:rails RAILS=4.1.10"
    - "TASK=test:rails RAILS=4.2.1"
    - "TASK=test:sinatra SINATRA=master"
    - "TASK=test:sinatra SINATRA=1.3.6"
    - "TASK=test:sinatra SINATRA=1.4.6"
    - "TASK=bench"
    - "TASK=bench slow=1"

matrix:
  exclude:
    - rvm: rbx-3
      env: "TASK=test:rails RAILS=master"
    - rvm: 2.0.0
      env: "TASK=test:rails RAILS=master"
    - rvm: 2.3.3
      env: "TASK=test:rails RAILS=3.1.12 TILT=1.3.4"
    - rvm: 2.3.3
      env: "TASK=test:rails RAILS=3.2.21 TILT=1.3.4"
  allow_failures:
    - env: "TASK=test:core_and_plugins TILT=master"
    - env: "TASK=test:rails RAILS=master"
    - env: "TASK=test:sinatra SINATRA=master"
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-head

notifications:
  irc: "chat.freenode.net#slim-lang"
